services:
  # Frontend - Responsabilidade: Interface do usuário
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - blog-network

  # Backend - Responsabilidade: Lógica de negócio e APIs
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/blogdb
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - blog-network

  # Database - Responsabilidade: Persistência de dados
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - blog-network

  # Cache - Responsabilidade: Cache e sessões
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge